---
   - name: mkdir for rails
     shell: mkdir /root/rails
     register: has_rails
     ignore_errors: True

   - name: Install Rails
     shell: gem install rails --no-ri --no-rdoc
     when: has_rails|success
