---
  - name: Install zabbix repo
    yum: name=http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm state=present

  - name: Install zabbix_agent
    yum: name=zabbix-agent  state=present

  - name: Set template file
    template: src=zabbix_agentd.j2 dest=/etc/zabbix/zabbix_agentd.conf owner=root group=root mode=0644

  - name: Service zabbix_agent restart
    service: name=zabbix-agent state=restarted enabled=yes
